version: '3.1'
services:
  postgre:
    image: 'postgres:13-alpine'
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=alma312
      - POSTGRES_DB=notiprice
  backendapp:
    container_name: notiprice
    image: notiprice:latest
    build: ./
    ports:
      - "3006:3006"
    depends_on:
      - postgre
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgre:5432/notiprice

